name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    env:
      DISCORD_TOKEN: ${{ env.DISCORD_TOKEN }}
      CLIENT_ID: ${{ env.CLIENT_ID }}
      DISCORD_SECRET: ${{ env.DISCORD_SECRET }}
      GUILD_ID: ${{ env.GUILD_ID }}
      DATABASE_CONNECTION: ${{ env.DATABASE_CONNECTION }}
      NEXT_SECRET: ${{ env.NEXT_SECRET }}
      NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run next:build
          start: npm run next:start
          wait-on: http://localhost:3000
          command: npm run e2e:headless
  cypress-run-no-auth:
    runs-on: ubuntu-20.04
    env:
      DISCORD_TOKEN: ${{ env.DISCORD_TOKEN }}
      CLIENT_ID: ${{ env.CLIENT_ID }}
      DISCORD_SECRET: ${{ env.DISCORD_SECRET }}
      GUILD_ID: ${{ env.GUILD_ID }}
      DATABASE_CONNECTION: ${{ env.DATABASE_CONNECTION }}
      NEXT_SECRET: ${{ env.NEXT_SECRET }}
      NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run next:build-auth
          start: npm run next:start-auth
          wait-on: http://localhost:3000
          command: npm run e2e:headless-auth