name: Unit tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Jest run
        run: npm run test
